### ISSUE TITLE
V2.8.3.2 on Win Can't Sign Tx w/Trezor and Keepkey

### ISSUE THREAD

**Issue by robdee** [pooler/electrum-ltc#49]
Both devices return " sign_tx() got an unexpected keyword argument 'lock_time' when attempting to sign a Transaction with the standalone and installer Windows executables downloaded from www.electrum-ltc.org

Trezor works fine on V2.6.4.2 but Keepkey returns "Error - Could not parse protocol buffer message" with Electrum failing to start.

Both devices work fine on V2.7.12 for btc.

**Comment by pooler** [comment]
Thanks for reporting. This is because version 0.7.13 of python-trezor is needed, but the build scripts still reference version 0.7.12. As for Keepkey, they haven't implemented lock_time support yet.
This issue is also present upstream, so ideally it should be fixed there.

**Comment by robdee** [comment]
Thanks pooler for acknowledging the deficits. I'm thinking of taking a stab at building the client with 0.7.13 and being very new at this will likely sink some hrs in. Any insight appreciated on why, given both Trezor and Keepkey can't send with the the latest Electrum version, the newer python-trezor package wasn't incorporated. In any event V2.8.3.2 now with watch-only wallet like the btc version and at least Keepkey working alongside Trezor is promising. Thx

**Comment by pooler** [comment]
The issue is not specific to the Litecoin port, it's also present upstream. The simplest explanation would be that they forgot to update the build script for Windows, as I'm not aware of any problem with the latest version of python-trezor. I plan on getting this fixed in the next beta release, by the way.

**Comment by pooler** [comment]
This should be fixed in version 2.8.3.4, please check it out. (You can download it from the [website](https://electrum-ltc.org).)

**Comment by robdee** [comment]
Problem-solved for both Trezor and Keepkey with 2.8.3.4 as tested on a Debian VM however both devices with the new client on Windows return "non-canonical DER signature (see attached).

![electrum-ltc-txerror](https://user-images.githubusercontent.com/29416405/27471559-18eee5a2-57c6-11e7-95ab-ae5daf871725.png)

**Comment by pooler** [comment]
Sorry about that, it should be fixed in version 2.8.3.5 which is already available for download.

**Comment by robdee** [comment]
No worries, I'll try the new Windows build tomorrow. I'm toast from ramping-up on Linux. Thanks.

**Comment by robdee** [comment]
Excellent V2.8.3.5. Now both Trezor and Keepkey can sign Tx and Messages on Windows. Thanks!
