### ISSUE TITLE
onchain_history jsonrpc command broken

### ISSUE THREAD

**Issue by alenkalac** [pooler/electrum-ltc#276]
Version 4.0.9.3

Running `onchain_history` with the `from_height` param breaks the code - This works fine with Electrum Bitcoin 4.1.5

```
curl --data-binary '{"jsonrpc":"2.0","id":"curltext","method":"onchain_history","params":{"from_height":2003174}}' http://root1:root1@localhost:7777 | json_pp

{
   "error" : {
      "code" : 1,
      "message" : "onchain_history() got an unexpected keyword argument 'from_height'"
   },
   "id" : "curltext",
   "jsonrpc" : "2.0"
}
```

I have tried all of the things I could think off - I need this functionality and I don't know how or why it's not working, 
comparing it to the btc counterpart - the code looks identical, so in theory it should work,

**Comment by alenkalac** [comment]
I see that in 4.0.9.3 the onchain_history is still using the old method without the from_height and to_height which was added back to btc electrum after some time. 

this code is in master branch on ltc electrum but it's unreleased - when is the next version expected to drop?

**Comment by pooler** [comment]
No date has been set for the next binary release, but you can of course use the code from the master branch if you need the new functionalities.

I'm going to close this ticket as you wrote that the issue has already been addressed in master.
